/**
 * Generate executive summary reports from KPI data
 */

import { loadKPIHistory } from './kpiHistory.js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Generate a text summary report
 */
export function generateTextReport(kpis, period) {
  const { overall, managerKPIs } = kpis;
  
  const report = `
╔════════════════════════════════════════════════════════════════╗
║           SLA PERFORMANCE REPORT                               ║
╚════════════════════════════════════════════════════════════════╝

PERIOD: ${period.start} to ${period.end}
GENERATED: ${new Date().toLocaleString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EXECUTIVE SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📊 Overall SLA Compliance Rate:  ${overall.complianceRate}%
${getRatingEmoji(parseFloat(overall.complianceRate))} ${getRatingText(parseFloat(overall.complianceRate))}

Total Tickets Processed:         ${overall.totalTickets}
✅ Met SLA:                       ${overall.metSLA} (${((overall.metSLA/overall.totalTickets)*100).toFixed(1)}%)
❌ Breached SLA:                  ${overall.breachedSLA} (${((overall.breachedSLA/overall.totalTickets)*100).toFixed(1)}%)
⏳ Pending Response:              ${overall.pendingSLA}

⏱️  Average Response Time:        ${overall.avgResponseTime}
🎯 SLA Goal:                      4 hours

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
MANAGER PERFORMANCE RANKINGS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${managerKPIs.map((m, i) => `
${i + 1}. ${m.manager.padEnd(20)} | ${m.complianceRate}% compliance
   ├─ Tickets: ${m.total}
   ├─ Met SLA: ${m.met}
   ├─ Breached: ${m.breached}
   ├─ Pending: ${m.pending}
   └─ Avg Response: ${m.avgResponseTime}
`).join('')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
KEY INSIGHTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${generateInsights(overall, managerKPIs)}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
RECOMMENDATIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${generateRecommendations(overall, managerKPIs)}

════════════════════════════════════════════════════════════════
Report generated by Jira Bug Metrics System
════════════════════════════════════════════════════════════════
`;
  
  return report;
}

/**
 * Generate CSV export for spreadsheet analysis
 */
export function generateCSVReport(kpis, period) {
  const { managerKPIs } = kpis;
  
  const headers = [
    'Manager',
    'Compliance Rate (%)',
    'Total Tickets',
    'Met SLA',
    'Breached SLA',
    'Pending',
    'Avg Response Time',
    'Period Start',
    'Period End'
  ];
  
  const rows = managerKPIs.map(m => [
    m.manager,
    m.complianceRate,
    m.total,
    m.met,
    m.breached,
    m.pending,
    m.avgResponseTime,
    period.start,
    period.end
  ]);
  
  const csv = [
    headers.join(','),
    ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
  ].join('\n');
  
  return csv;
}

/**
 * Generate quarterly comparison report
 */
export function generateQuarterlyReport() {
  const history = loadKPIHistory();
  
  if (history.snapshots.length < 2) {
    return 'Insufficient data for quarterly comparison. Need at least 2 snapshots.';
  }
  
  // Group by quarter
  const quarters = {};
  history.snapshots.forEach(s => {
    const date = new Date(s.period.start);
    const year = date.getFullYear();
    const quarter = Math.floor(date.getMonth() / 3) + 1;
    const key = `${year}-Q${quarter}`;
    
    if (!quarters[key]) {
      quarters[key] = [];
    }
    quarters[key].push(s);
  });
  
  const quarterlyStats = Object.entries(quarters).map(([quarter, snapshots]) => {
    const avgCompliance = snapshots.reduce((sum, s) => 
      sum + parseFloat(s.kpis.overall.complianceRate), 0
    ) / snapshots.length;
    
    return {
      quarter,
      avgCompliance: avgCompliance.toFixed(1),
      snapshots: snapshots.length,
      totalTickets: snapshots.reduce((sum, s) => sum + s.kpis.overall.totalTickets, 0)
    };
  }).sort((a, b) => a.quarter.localeCompare(b.quarter));
  
  let report = `
╔════════════════════════════════════════════════════════════════╗
║           QUARTERLY PERFORMANCE COMPARISON                     ║
╚════════════════════════════════════════════════════════════════╝

GENERATED: ${new Date().toLocaleString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
QUARTERLY SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${quarterlyStats.map(q => `
${q.quarter}
  Avg Compliance: ${q.avgCompliance}%
  Total Tickets: ${q.totalTickets}
  Collections: ${q.snapshots}
`).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
QUARTER-OVER-QUARTER TRENDS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

`;
  
  for (let i = 1; i < quarterlyStats.length; i++) {
    const current = quarterlyStats[i];
    const previous = quarterlyStats[i - 1];
    const change = parseFloat(current.avgCompliance) - parseFloat(previous.avgCompliance);
    const arrow = change > 0 ? '↑' : change < 0 ? '↓' : '→';
    const status = change > 0 ? '✅ IMPROVED' : change < 0 ? '⚠️ DECLINED' : '→ STABLE';
    
    report += `
${previous.quarter} → ${current.quarter}
  ${arrow} ${Math.abs(change).toFixed(1)}% change (${previous.avgCompliance}% → ${current.avgCompliance}%)
  ${status}
`;
  }
  
  report += `
════════════════════════════════════════════════════════════════
`;
  
  return report;
}

/**
 * Save report to file
 */
export function saveReport(content, filename) {
  const reportsDir = path.join(__dirname, '..', 'reports');
  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir);
  }
  
  const filepath = path.join(reportsDir, filename);
  fs.writeFileSync(filepath, content);
  
  console.log(`Report saved to: ${filepath}`);
  return filepath;
}

// Helper functions

function getRatingEmoji(rate) {
  if (rate >= 85) return '🟢';
  if (rate >= 70) return '🟡';
  return '🔴';
}

function getRatingText(rate) {
  if (rate >= 85) return 'EXCELLENT PERFORMANCE';
  if (rate >= 70) return 'GOOD PERFORMANCE';
  return 'NEEDS IMPROVEMENT';
}

function generateInsights(overall, managerKPIs) {
  const insights = [];
  const rate = parseFloat(overall.complianceRate);
  
  // Overall performance insight
  if (rate >= 85) {
    insights.push('✓ Team is exceeding SLA compliance targets');
  } else if (rate >= 70) {
    insights.push('✓ Team is meeting acceptable compliance levels');
    insights.push(`• ${(85 - rate).toFixed(1)}% improvement needed to reach excellent rating`);
  } else {
    insights.push('⚠ Team compliance is below acceptable threshold');
    insights.push(`• ${(70 - rate).toFixed(1)}% improvement needed to reach good rating`);
  }
  
  // Manager performance spread
  const rates = managerKPIs.map(m => parseFloat(m.complianceRate));
  const highest = Math.max(...rates);
  const lowest = Math.min(...rates);
  const spread = highest - lowest;
  
  if (spread > 30) {
    insights.push(`• High variance in manager performance (${spread.toFixed(1)}% spread)`);
    insights.push('  → Consider knowledge sharing from top performers');
  } else {
    insights.push(`• Consistent performance across managers (${spread.toFixed(1)}% spread)`);
  }
  
  // Top performers
  const topPerformers = managerKPIs.filter(m => parseFloat(m.complianceRate) >= 85);
  if (topPerformers.length > 0) {
    insights.push(`• ${topPerformers.length} manager(s) achieving excellent compliance`);
  }
  
  // Breach analysis
  const breachRate = (overall.breachedSLA / overall.totalTickets) * 100;
  if (breachRate > 30) {
    insights.push(`⚠ High breach rate (${breachRate.toFixed(1)}%) indicates response capacity issues`);
  }
  
  return insights.join('\n');
}

function generateRecommendations(overall, managerKPIs) {
  const recommendations = [];
  const rate = parseFloat(overall.complianceRate);
  
  if (rate < 70) {
    recommendations.push('1. PRIORITY: Improve initial response times');
    recommendations.push('   • Set up response templates for faster initial contact');
    recommendations.push('   • Ensure adequate coverage during business hours');
    recommendations.push('   • Consider SLA monitoring alerts');
  } else if (rate < 85) {
    recommendations.push('1. Continue improving response consistency');
    recommendations.push('   • Focus on reducing response time variance');
  } else {
    recommendations.push('1. Maintain current excellent performance');
    recommendations.push('   • Document best practices for team reference');
  }
  
  // Manager-specific
  const lowPerformers = managerKPIs.filter(m => parseFloat(m.complianceRate) < 70);
  if (lowPerformers.length > 0) {
    recommendations.push(`\n2. Manager coaching needed for ${lowPerformers.length} team member(s)`);
    lowPerformers.forEach(m => {
      recommendations.push(`   • ${m.manager}: ${m.complianceRate}% compliance`);
    });
  }
  
  // Response time
  const avgMinutes = overall.avgResponseTime;
  if (avgMinutes.includes('h')) {
    const hours = parseInt(avgMinutes.split('h')[0]);
    if (hours > 4) {
      recommendations.push('\n3. Average response time exceeds SLA goal');
      recommendations.push('   • Review ticket routing and assignment processes');
      recommendations.push('   • Consider automated assignment rules');
    }
  }
  
  recommendations.push('\n4. Track progress with regular metrics collection');
  recommendations.push('   • Weekly collections recommended for trend analysis');
  recommendations.push('   • Set quarterly improvement targets');
  
  return recommendations.join('\n');
}
